### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by Nikey646** [danejur/AniDroid#1]
https://github.com/danejur/AniDroid/blob/98403188520ffe3454f977a571404142af60b9e1/AniDroid/AniDroid.csproj#L429

The AniDroid.csproj references a file that is not inside of the repo.

**Comment by danejur** [comment]
RESOLVED

**Comment by Nikey646** [comment]
Shitty dev doesn't even link the commit or marks the issue resolved via the commit message.
f42295e1223ed98b13b3313d207e1914411937a3
