### ISSUE TITLE
Add sorting by time until next release

### ISSUE THREAD

**Issue by milten89** [danejur/AniDroid#2]
First of all great app for tracking releases. Good job 👍 

I miss one feature that is sorting anime on Watching list by next episode release date. 

On example screenshoot list is sorted by default.
![Screenshot_2020-08-31-12-43-56-526_com jurasdev anidroid](https://user-images.githubusercontent.com/9992006/91712424-00d10780-eb88-11ea-9f1b-7068e06aad3e.jpg)

This new method of sorting should return list in ascending order:
1. THE GOD OF HIGH SCHOOL
2. Black Clover
3. Re:Zero
4. Deka-Dence
5. etc.

Is this is possible to add?

**Comment by danejur** [comment]
Somehow I was never notified of this issue. This should be a pretty easy thing to add, so I'll work on it tonight.

**Comment by danejur** [comment]
Added with latest release.
