### ISSUE TITLE
EditText in media lists never loses focus

### ISSUE THREAD

**Issue by ddmgy** [danejur/AniDroid#3]
Whenever I either open AniDroid for the first time or navigate from another app back to AniDroid, the EditText used to filter media lists will grab focus and pull up the on-screen keyboard. Nothing I do (navigating to another section in the app, tapping on a list item, etc.) seems to cause it to lose focus.

I'm using the latest version released on the Play store, version .9.16.1. This behavior is present on Android 6.0 and 8.1.

On another note, I've been using AniDroid for a couple of years and really enjoy it.

**Comment by danejur** [comment]
I haven't worked on AniDroid in a couple months, but am starting up again now. I took a brief look at this back when the issue was opened, and tried a couple quick fixes, but couldn't find a good way to solve the issue. I'll be putting some more time into finding a fix shortly.

**Comment by danejur** [comment]
Fixed in 4a77895f2d4e326efae6f08c29ae818115bab4e4

**Comment by ddmgy** [comment]
Perfect, thanks!
