### ISSUE TITLE
Rewatching an anime causes finish date to change

### ISSUE THREAD

**Issue by LitDub** [danejur/AniDroid#5]
Completing a rewatch/reread of an anime or manga causes the finish date to change to the current date. This is distinct from Anilist's normal behavior, which leaves the finish date as the date of the first completion.

This has caused me to lose records of my initial completion of some of my favorite anime :(. First world problems I know. Still a great app, don't get me wrong. Used it for two years now.

**Comment by danejur** [comment]
Hm, sorry to hear this happened. I'll get a fix in ASAP (also sorry that this is like 2 months old, I have a 2 year old, sue me 🙃).

**Comment by danejur** [comment]
Fixed in 05af923e081024f71c71bda8d39e126e57885970
